### ISSUE TITLE
Can I use this to distinguish black people?

### ISSUE THREAD

**Issue by Kwansy98** [chiyeung54526/face-detect-base-on-skin-color#1]

**Comment by chiyeung54526** [comment]
sure

**Comment by chiyeung54526** [comment]
I will upload an example for reference

**Comment by Kwansy98** [comment]
thank you sir

**Comment by Kwansy98** [comment]
very cool, hope Guangzhou no 镍铬 anymore

**Comment by claw6148** [comment]
keep tracking this issue. cantonese must be detectable.

**Comment by Kwansy98** [comment]
> keep tracking this issue. cantonese must be detectable.

i guess you mean cantonig?
